### ISSUE TITLE
redesign with vectors

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#258]
@graemeblair  can you add help in documentation  on how to redesign with a set of vectors
here the argument is a vector and we want two designs with different vectors, but 
eg redesign(design, block_probs = c(c(.1,.2, .3), c(.1,.3, .2))

is surely not right; do users use list or sthg else?

eg help has

design_vary_N <- redesign(design, n = seq(400, 900, 100))

but what if you want to indicate not 6 designs but one design in which n is a vector (say of sizes for level 2.

**Comment by macartan** [comment]
The following bad behavior by reshape_diagnosis is perhaps related:

Here 9 designs are created (as they should be) but the  display of parameters is a mess because it is treated a vector of parameters for a vector of designs as a vector of parameters for one design.
```
cluster_designs <- expand_design(
           block_cluster_two_arm_designer,
           N_clusters_in_block = c(4:10, 20, 30), 
           N_i_in_cluster      = 5,
           control_mean = 0, treatment_mean = 0,
           sd_block = 0, sd_cluster = .5^.5, sd_i_0 = .5^.5)

> reshape_diagnosis(diagnoses)[,6:7]
   N_clusters_in_block N_i_in_cluster
1                 4:10              5
2                 4:10              5
3                   20              5
4                   20              5
5                   30              5
6                   30              5
7                 <NA>             NA
8                 <NA>             NA
9                 <NA>             NA
10                <NA>             NA
11                <NA>             NA
12                <NA>             NA
13                <NA>             NA
14                <NA>             NA
15                <NA>             NA
16                <NA>             NA
17                <NA>             NA
18                <NA>             NA
```

**Comment by nfultz** [comment]
list(prob1, prob2)

e: I'll just use the internal function.

also comment 2 should be fixed in #241

**Comment by macartan** [comment]
Agree on the way redesign works. But still not sure how to use either redesign or expand design to alter a vector argument:


```
library(DesignLibrary)

# This correctly produces one design with two blocks of different size
design <- block_cluster_two_arm_designer(N_blocks = 2, N_clusters_in_block = c(4,5))

# Question is how to do it using redeseign or expand design

# This produces two designs when we (might)  want just one
design <- redesign(block_cluster_two_arm_designer(N_blocks = 2), N_clusters_in_block = c(4,5))

# This produces two designs when we (might)  want just one
design <- expand_design(block_cluster_two_arm_designer, N_blocks = 2, N_clusters_in_block = c(4,5))

# This doesn't work
design <-expand_design(block_cluster_two_arm_designer, N_blocks = 2, N_clusters_in_block = list(c(4,5)))
design

# I think this is close to what Neal was suggesting bu is same as above and doesn't work for me
design <- expand_design(
  function(N_clusters_in_block)
    redesign(block_cluster_two_arm_designer(N_blocks = 2),
             N_clusters_in_block = N_clusters_in_block),
  N_clusters_in_block = list(c(4, 5))
)
design
```

Do we have a way to indicate that a vector is to be changed once rather than a scalar multiple times?

**Comment by nfultz** [comment]
This is working, but there's some subtlety to it - suggest using the non variadic functions if you want more control.

```
> z <- 1:5
> dsn <- declare_population(1, a=mean(z)) + NULL
> lapply(redesign(dsn, z=list(3:5, 4:10)), draw_data)
$design_1
  ID a
1  1 4

$design_2
  ID a
1  1 7
> draw_data(dsn)
  ID a
1  1 3
> z
[1] 1 2 3 4 5
```

**Comment by acoppock** [comment]
note to self: we need a serious improvement to the test suite for all these cases
