### ISSUE TITLE
default values for handlers not picked up in declarations?

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#457]
```
f <- function(N = 10, a = 1) data.frame(X = rep(a, N))
  
# This works
declare_population(handler = f, N = 3, a = 2)()

# This works
declare_population(data = f())()

# This doesn't
declare_population(handler = f, N = 3)()
```

**Comment by nfultz** [comment]
I'm not seeing an error on my build of 0.23 -

```{r}
##------ Sun Dec 13 22:03:36 2020 ------##
> require(DeclareDesign)
Loading required package: DeclareDesign
Loading required package: randomizr
Loading required package: fabricatr
Loading required package: estimatr
> f <- function(N = 10, a = 1) data.frame(X = rep(a, N))
>   
> # This works
> declare_population(handler = f, N = 3, a = 2)()
  X
1 2
2 2
3 2
> 
> # This works
> declare_population(data = f())()
   X
1  1
2  1
3  1
4  1
5  1
6  1
7  1
8  1
9  1
10 1
> 
> # This doesn't
> declare_population(handler = f, N = 3)()
  X
1 1
2 1
3 1
```

can you post your `sessionInfo()` - this may have been fixed in the last dplyr patch.

Also note that handlers are supposed to have a data argument even if it isn't used, eg

```
f2 <- function(data, N = 10, a = 1) data.frame(X = rep(a, N))
```

That requirement is somewhat relaxed now that dplyr and base functions are allowed to be handlers also.

**Comment by gerasy1987** [comment]
It seems that this still does not work properly in 0.24.0 build:

```
> library(DeclareDesign)
Loading required package: randomizr
Loading required package: fabricatr
Loading required package: estimatr
> f <- function(N = 10, a = 1) data.frame(X = rep(a, N))
> declare_population(handler = f, N = 3, a = 2)()
  X
1 2
2 2
3 2
> declare_population(data = f())()
   X
1  1
2  1
3  1
4  1
5  1
6  1
7  1
8  1
9  1
10 1
> declare_population(handler = f, N = 3)()
data frame with 0 columns and 0 rows
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: elementary OS 5.1.7 Hera

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] DeclareDesign_0.24.0 estimatr_0.28.0      fabricatr_0.10.0     randomizr_0.20.0    

loaded via a namespace (and not attached):
 [1] splines_4.0.3          network_1.16.1         functional_0.6         Formula_1.2-4         
 [5] latticeExtra_0.6-29    yaml_2.2.1             robustbase_0.93-6      pillar_1.4.7          
 [9] backports_1.2.1        lattice_0.20-41        glue_1.4.2             sspse_0.6             
[13] digest_0.6.27          RColorBrewer_1.1-2     checkmate_2.0.0        colorspace_2.0-0      
[17] htmltools_0.5.0        Matrix_1.2-18          plyr_1.8.6             lpSolve_5.6.15        
[21] pkgconfig_2.0.3        bookdown_0.21          purrr_0.3.4            ergm_3.11.0           
[25] scales_1.1.1           MultiRNG_1.2.3         chords_0.95.4          jpeg_0.1-8.1          
[29] tibble_3.0.4           htmlTable_2.1.0        mgcv_1.8-33            generics_0.1.0        
[33] ggplot2_3.3.2          ellipsis_0.3.1         nnet_7.3-14            lazyeval_0.2.2        
[37] survival_3.2-7         magrittr_2.0.1         crayon_1.3.4           statnet.common_4.4.1  
[41] evaluate_0.14          nlme_3.1-151           MASS_7.3-53            foreign_0.8-79        
[45] RDS_0.9-2              tools_4.0.3            data.table_1.13.4      lifecycle_0.2.0       
[49] stringr_1.4.0          networkreporting_0.1.1 trust_0.1-8            munsell_0.5.0         
[53] cluster_2.1.0          scam_1.2-9             compiler_4.0.3         rlang_0.4.9           
[57] grid_4.0.3             rstudioapi_0.13        htmlwidgets_1.5.3      igraph_1.2.6          
[61] base64enc_0.1-3        rmarkdown_2.5          gtable_0.3.0           reshape2_1.4.4        
[65] R6_2.5.0               gridExtra_2.3          rle_0.9.2              knitr_1.30            
[69] dplyr_1.0.2            Hmisc_4.4-2            surveybootstrap_0.0.1  stringi_1.5.3         
[73] parallel_4.0.3         hiddenmeta_0.0.8       Rcpp_1.0.5             vctrs_0.3.5           
[77] fastDummies_1.6.3      rpart_4.1-15           png_0.1-7              DEoptimR_1.0-8        
[81] tidyselect_1.1.0       xfun_0.19              coda_0.19-4 
```

**Comment by nfultz** [comment]
Handler functions are supposed to have a data argument, like this

 f2 <- function(data, N = 10, a = 1) data.frame(X = rep(a, N))


* If the handler doesn't have a data argument, like dplyr functions, data
will match the first free argument positionally when the step is declared.
(eg use .data on dplyr) using match.call.

* Additionally, if you don't provide a data argument to the step, it
defaults to NULL.

* Those together imply the result is f(N=3, NULL) and not f(N=3, a=1)


EDIT:

For functions that can't accept a data argument, I'd recommend passing the function call to the data argument of the step, maybe quoted, eg

```
> f <- function(N = 10, a = 1) data.frame(X = rnorm(mean=a, N))
> s1 <- declare_population(data = f())
> s2 <- declare_population(data = !!f())
```

Note how the RNG advances when re-executing  s1 but not s2.

**Comment by graemeblair** [comment]
note: add error/warning at declare time to tell user that there is not a data argument and improve docs
